# Generated by Django 3.2 on 2023-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithrole',
            name='companyname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
