# Generated by Django 3.2 on 2023-06-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0003_alter_candidates_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithrole',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
